### ISSUE TITLE
Read in post data

### ISSUE THREAD

**Issue by soonernotfaster** [steven-solomon/dataschool#1]
# Goal
Enable EDA of posts using Sklearn by reading in and cleaning post data.

# Tasks

- [ ] Read in file
- [ ] Clean file contents
  - [ ] Count number of code blocks
  - [ ] Remove code blocks
  - [ ] Count number of links
  - [ ] Remove links
  - [ ] Count total number of words (excluding code blocks) 
  - [ ] Remove frontmatter
